import type { FlatProfile, PortalName } from './types';

export const VERSION = '0.1.0';

export const PORTAL_URLS: Record<PortalName, string[]> = {
  linkedin: ['linkedin.com/jobs', 'linkedin.com/in'],
  naukri: ['naukri.com'],
  wellfound: ['wellfound.com', 'angel.co'],
  instahyre: ['instahyre.com'],
  greenhouse: ['greenhouse.io', 'boards.greenhouse.io'],
  lever: ['jobs.lever.co', 'lever.co'],
  workday: ['myworkdayjobs.com', 'workday.com'],
  generic: [],
};

export interface AtsSelectors {
  nextButton: string;
  submitButton: string;
  formContainer: string;
}

export const ATS_SELECTORS: Record<string, AtsSelectors> = {
  greenhouse: {
    nextButton: 'button[type=submit]',
    submitButton: '#submit_app',
    formContainer: '#application_form',
  },
  lever: {
    nextButton: 'button.template-btn-submit',
    submitButton: 'button.postings-btn-submit',
    formContainer: 'form.posting-application-form',
  },
  workday: {
    nextButton: 'button[data-automation-id="bottom-navigation-next-button"]',
    submitButton:
      'button[data-automation-id="bottom-navigation-next-button"][aria-label*="Submit"]',
    formContainer: 'div[data-automation-id="applyFlowPage"]',
  },
  linkedin: {
    nextButton: 'button[aria-label="Continue to next step"]',
    submitButton: 'button[aria-label="Submit application"]',
    formContainer: '.jobs-easy-apply-modal',
  },
};

export const UNKNOWN_FIELD_HIGHLIGHT_STYLE =
  'outline: 2px solid #f97316 !important; outline-offset: 2px; background-color: #fff7ed !important;';

export const FILLED_FIELD_HIGHLIGHT_STYLE =
  'outline: 1px solid #86efac !important; outline-offset: 1px; background-color: #f0fdf4 !important;';

export const FIELD_LABEL_MAP: Record<keyof FlatProfile, string[]> = {
  // Personal
  fullName: [
    'full name',
    'your name',
    'applicant name',
    'name',
    'candidate name',
    'first and last name',
    'legal name',
    'complete name',
    'name as per records',
  ],
  firstName: [
    'first name',
    'given name',
    'fname',
    'forename',
    'first',
    'given names',
    'first name as per aadhaar',
  ],
  lastName: [
    'last name',
    'surname',
    'family name',
    'lname',
    'last',
    'family names',
    'last name as per aadhaar',
  ],
  email: [
    'email',
    'email address',
    'e-mail',
    'work email',
    'personal email',
    'contact email',
    'primary email',
    'email id',
    'mail id',
  ],
  phone: [
    'phone',
    'mobile',
    'phone number',
    'mobile number',
    'contact number',
    'whatsapp number',
    'telephone',
    'cell phone',
    'contact no',
    'mobile no',
  ],
  city: [
    'city',
    'current city',
    'location',
    'current location',
    'town',
    'residence city',
    'home city',
    'city of residence',
  ],
  state: [
    'state',
    'province',
    'region',
    'state province',
    'state of residence',
    'current state',
  ],
  country: [
    'country',
    'country of residence',
    'nationality',
    'country of origin',
    'home country',
    'current country',
  ],
  linkedinUrl: [
    'linkedin',
    'linkedin url',
    'linkedin profile',
    'linkedin link',
    'linkedin profile url',
    'linkedin page',
    'linkedin id',
  ],
  githubUrl: [
    'github',
    'github url',
    'github profile',
    'github link',
    'github profile url',
    'github username',
    'github handle',
  ],
  portfolioUrl: [
    'portfolio',
    'portfolio url',
    'website',
    'personal website',
    'personal site',
    'portfolio link',
    'portfolio website',
    'blog url',
  ],
  twitterUrl: [
    'twitter',
    'twitter url',
    'twitter profile',
    'twitter link',
    'twitter handle',
    'x profile',
    'x url',
    'x handle',
  ],

  // Professional
  currentTitle: [
    'current designation',
    'current role',
    'job title',
    'current position',
    'designation',
    'present designation',
    'current job title',
    'role at current company',
    'present role',
  ],
  currentCompany: [
    'current company',
    'current employer',
    'employer',
    'company name',
    'organisation',
    'organization',
    'present company',
    'present employer',
    'working at',
  ],
  totalYearsExp: [
    'years of experience',
    'total experience',
    'work experience',
    'experience',
    'years exp',
    'relevant experience',
    'total years',
    'years of work experience',
    'professional experience',
    'overall experience',
  ],
  noticePeriod: [
    'notice period',
    'notice period (days)',
    'notice period (weeks)',
    'joining time',
    'available from',
    'earliest joining',
    'serving notice',
    'notice period in days',
    'availability',
    'when can you join',
  ],
  currentCTC: [
    'current ctc',
    'current salary',
    'current package',
    'ctc',
    'annual ctc',
    'fixed ctc',
    'cost to company',
    'present ctc',
    'current compensation',
    'salary in lpa',
    'current annual salary',
  ],
  expectedCTC: [
    'expected ctc',
    'expected salary',
    'salary expectation',
    'desired salary',
    'expected package',
    'expected compensation',
    'salary expected',
    'desired ctc',
    'expected annual salary',
    'salary requirement',
  ],
  workAuthorization: [
    'work authorization',
    'work permit',
    'visa status',
    'right to work',
    'authorized to work',
    'work eligibility',
    'legally authorized',
    'immigration status',
    'work visa',
  ],
  willingToRelocate: [
    'willing to relocate',
    'open to relocation',
    'can relocate',
    'relocation',
    'ready to relocate',
    'open to relocate',
    'willing to move',
    'relocation willingness',
  ],
  preferredLocations: [
    'preferred location',
    'preferred locations',
    'desired location',
    'job location preference',
    'open to locations',
    'location preference',
    'preferred work location',
    'target locations',
    'cities interested in',
  ],

  // Skills and languages
  skills: [
    'skills',
    'technical skills',
    'key skills',
    'core skills',
    'skill set',
    'technologies',
    'tech stack',
    'competencies',
    'primary skills',
    'professional skills',
  ],
  languages: [
    'languages',
    'language proficiency',
    'languages known',
    'spoken languages',
    'language skills',
    'languages spoken',
    'known languages',
    'language fluency',
  ],

  // Education (first entry)
  degree: [
    'degree',
    'qualification',
    'highest qualification',
    'education level',
    'degree name',
    'highest degree',
    'academic qualification',
    'education qualification',
  ],
  field: [
    'field of study',
    'major',
    'specialization',
    'stream',
    'branch',
    'discipline',
    'area of study',
    'subject',
    'specialisation',
  ],
  institution: [
    'institution',
    'university',
    'college',
    'school',
    'institute',
    'institution name',
    'educational institution',
    'alma mater',
    'college name',
  ],
  graduationYear: [
    'graduation year',
    'year of passing',
    'passing year',
    'year of graduation',
    'batch',
    'year completed',
    'pass out year',
    'year of completion',
  ],
  percentage: [
    'percentage',
    'cgpa',
    'gpa',
    'marks',
    'grade',
    'aggregate',
    'score',
    'academic score',
    'final grade',
    'percentile',
  ],

  // Experience (first entry)
  title: [
    'previous job title',
    'past designation',
    'role title',
    'position held',
    'employment title',
    'work title',
    'job role',
    'position title',
    'designation held',
  ],
  company: [
    'previous company',
    'past employer',
    'organization',
    'employer name',
    'company worked at',
    'former employer',
    'previous employer',
    'organisation name',
    'worked at',
  ],
  startDate: [
    'start date',
    'from',
    'date from',
    'employment start',
    'joined on',
    'work start date',
    'from date',
    'start month',
    'date started',
  ],
  endDate: [
    'end date',
    'to',
    'date to',
    'employment end',
    'left on',
    'work end date',
    'to date',
    'end month',
    'date ended',
  ],
  current: [
    'currently working',
    'present employer',
    'i currently work here',
    'still working',
    'current employment',
    'working here currently',
    'is current role',
    'presently employed',
  ],
  description: [
    'job description',
    'role description',
    'responsibilities',
    'work summary',
    'duties',
    'achievements',
    'work experience description',
    'role summary',
    'key responsibilities',
    'job duties',
  ],
};
